# Generated by Django 3.1.2 on 2021-05-01 09:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CYO', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adventure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('title', models.TextField(max_length=255)),
                ('adventure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Events', to='CYO.adventure')),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition_amount', models.IntegerField(default=0)),
                ('text', models.TextField()),
                ('final', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='End', to='CYO.event')),
                ('initial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Start', to='CYO.event')),
            ],
        ),
        migrations.AddField(
            model_name='adventure',
            name='endevent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='End_screen', to='CYO.event'),
        ),
        migrations.AddField(
            model_name='adventure',
            name='startevent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='First_screen', to='CYO.event'),
        ),
        migrations.AddField(
            model_name='adventure',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Creations', to=settings.AUTH_USER_MODEL),
        ),
    ]
