# Generated by Django 3.1.2 on 2021-05-17 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CYO', '0002_auto_20210501_1221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='condition_amount',
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=64)),
                ('type', models.CharField(choices=[('Stat', 'Status'), ('Item', 'Item'), ('Hidden', 'Hidden Trigger'), ('Init', 'Initialization')], default='Stat', max_length=64)),
                ('hidden', models.BooleanField(default=False)),
                ('amount', models.IntegerField()),
                ('adventure', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Items', to='CYO.adventure')),
                ('choice', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Conditions', to='CYO.choice')),
            ],
        ),
    ]
