# Generated by Django 3.1.2 on 2021-05-17 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CYO', '0003_auto_20210517_1201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='adventure',
        ),
        migrations.AddField(
            model_name='item',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Items', to='CYO.event'),
        ),
    ]
