# Generated by Django 3.1.2 on 2021-05-21 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CYO', '0004_auto_20210517_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='adventure',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='All_Items', to='CYO.adventure'),
        ),
        migrations.AlterField(
            model_name='item',
            name='type',
            field=models.CharField(choices=[('Status', 'Status'), ('Item', 'Item'), ('Hidden', 'Hidden Trigger')], default='Status', max_length=64),
        ),
    ]
