# Generated by Django 3.1.2 on 2021-05-23 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CYO', '0005_auto_20210521_1126'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='adventure',
        ),
        migrations.RemoveField(
            model_name='item',
            name='name',
        ),
        migrations.RemoveField(
            model_name='item',
            name='type',
        ),
        migrations.AlterField(
            model_name='adventure',
            name='startevent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='First_screen', to='CYO.event'),
        ),
        migrations.CreateModel(
            name='Item_Style',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=64)),
                ('type', models.CharField(choices=[('Status', 'Status'), ('Item', 'Item'), ('Hidden', 'Hidden Trigger')], default='Status', max_length=64)),
                ('adventure', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='All_Items', to='CYO.adventure')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='item_style',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='Instances', to='CYO.item_style'),
            preserve_default=False,
        ),
    ]
